using System.Diagnostics;

namespace Phelix.Core.Telemetry;

/// <summary>
/// Owns the application's single <see cref="ActivitySource"/> and defines all span
/// and tag name constants used across the codebase.
/// </summary>
/// <remarks>
/// Consumers reference constants via the nested <see cref="Spans"/> and <see cref="Tags"/>
/// classes so call sites are self-documenting without opening this file.
/// Example: <c>PhelixTelemetry.Tags.Tool.Success</c> is unambiguous at a glance.
/// </remarks>
public static class PhelixTelemetry
{
    /// <summary>The name used to register the <see cref="ActivitySource"/> with the OTel SDK.</summary>
    public const string SourceName = "Phelix";

    /// <summary>The single source for all Phelix-emitted spans.</summary>
    public static readonly ActivitySource Source = new(SourceName, "0.1");

    /// <summary>Span names.</summary>
    public static class Spans
    {
        /// <summary>Span wrapping one full agent loop turn, from user input to final reply.</summary>
        public const string Turn     = "phelix.agent.turn";

        /// <summary>Span wrapping a single tool dispatch within a turn.</summary>
        public const string ToolCall = "phelix.tool.call";
    }

    /// <summary>Tag (attribute) name constants, grouped by the span they appear on.</summary>
    public static class Tags
    {
        /// <summary>Tags set on <see cref="Spans.Turn"/>.</summary>
        public static class Turn
        {
            /// <summary>The model ID reported by the provider for the turn's final response; string.</summary>
            public const string ModelId      = "phelix.turn.model_id";

            /// <summary>The number of tool-call rounds that occurred during the turn; int.</summary>
            public const string ToolTurns    = "phelix.turn.tool_turns";

            /// <summary>Total tokens sent to the model this turn, aggregated across all inner calls; int.</summary>
            public const string InputTokens  = "gen_ai.usage.input_tokens";

            /// <summary>Total tokens generated by the model this turn, aggregated across all inner calls; int.</summary>
            public const string OutputTokens = "gen_ai.usage.output_tokens";
        }

        /// <summary>Tags set on <see cref="Spans.ToolCall"/>.</summary>
        public static class Tool
        {
            /// <summary>The name of the tool that was invoked; string.</summary>
            public const string Name    = "phelix.tool.name";

            /// <summary>Whether the tool dispatch succeeded — <c>true</c> if a registered tool was found and called; bool.</summary>
            public const string Success = "phelix.tool.success";

            /// <summary>The error message when dispatch failed (no registered tool matched); string. Absent on success.</summary>
            public const string Error   = "phelix.tool.error";
        }
    }
}
