namespace Phelix.Core.Session;

/// <summary>
/// Aggregate token counts for a single turn across all inner model calls.
/// </summary>
/// <remarks>
/// A turn may involve multiple model calls (one per tool-call round plus the final response).
/// Both counts are summed across all of those calls before being stored here.
/// </remarks>
public readonly record struct UsageSummary(
    /// <summary>
    /// Total tokens sent to the model this turn, including all conversation history and
    /// tool results, aggregated across all inner model calls.
    /// </summary>
    int InputTokens,

    /// <summary>
    /// Total tokens generated by the model this turn, aggregated across all inner model
    /// calls (tool-call responses and the final reply).
    /// </summary>
    int OutputTokens
);
